import type { Config } from "tailwindcss";

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "../src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        hs: {
          obsidian: "#141414",
          "great-white": "#dfe3eb",
          lorax: "#ff7a59",
          "calypso-medium": "#7fd1de",
          "calypso-selected-bg": "#e8f4f7",
          pantera: "#141414",
          "text-subtle": "#6b7280",
          "caution-border": "#f59e0b",
          "caution-fill": "#fffbeb",
          "radio-border": "#7c98b6",
          "radio-checked": "#4abacd",
          "radio-disabled-bg": "#eaf0f6",
          "radio-disabled-border": "#cbd6e2",
          "fill-primary-default": "#141414",
          "fill-secondary-default": "#fff",
          "border-secondary-default": "#8a8a8a",
          "fill-primary-disabled": "#f5f5f5",
          "text-primary-disabled": "#8a8a8a",
          focus: "#00a4bd",
          "text-alert-default": "#d9002b",
          "text-required-default": "#ff7a59",
          "border-alert-default": "#d9002b",
          "fill-field-default-alt": "#ffffff",
          "icon-interactive-default": "#141414",
        },
      },
      borderRadius: {
        "0": "0",
        "100": "4px",
        "300": "8px",
        "transitional-floating": "16px",
      },
      spacing: {
        "space-0": "0",
        "space-25": "1px",
        "space-50": "2px",
        "space-100": "4px",
        "space-200": "8px",
        "space-250": "10px",
        "space-300": "12px",
        "space-400": "16px",
        "space-500": "20px",
        "space-600": "24px",
        "space-700": "28px",
        "space-800": "32px",
        "space-900": "36px",
        "space-1000": "40px",
        "space-1100": "48px",
        "space-1200": "56px",
        "space-1300": "60px",
        "space-1400": "64px",
        "space-1500": "96px",
        "space-1600": "144px",
        "space-1700": "192px",
      },
      fontFamily: {
        lexend: ['"Lexend Deca"', "sans-serif"],
      },
      fontSize: {
        "heading-300": ["20px", { lineHeight: "24px" }],
        "heading-400": ["22px", { lineHeight: "27px" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
